# Options for analysis running.
run:
  timeout: 2m
  tests: false
  skip-dirs:
    - pkg/clinical/presentation/graph/
  
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - revive
    - funlen
    - gofmt
    - unparam
    - dupl
    - errorlint
    - bodyclose
    - contextcheck
    - gocritic
    - nilerr
    - ireturn
    - importas
    - wsl
    - revive

linters-settings:
  staticcheck:
    checks: ["all"]
  funlen:
    lines: -1 
    statements: -1
  