package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/savannahghi/clinical/pkg/clinical/application/common"
	"github.com/savannahghi/clinical/pkg/clinical/domain"
	"github.com/savannahghi/clinical/pkg/clinical/presentation/graph/generated"
)

// StartEpisodeByOtp is the resolver for the startEpisodeByOTP field.
func (r *mutationResolver) StartEpisodeByOtp(ctx context.Context, input domain.OTPEpisodeCreationInput) (*domain.EpisodeOfCarePayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.StartEpisodeByOtp(ctx, input)
}

// StartEpisodeByBreakGlass is the resolver for the startEpisodeByBreakGlass field.
func (r *mutationResolver) StartEpisodeByBreakGlass(ctx context.Context, input domain.BreakGlassEpisodeCreationInput) (*domain.EpisodeOfCarePayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.StartEpisodeByBreakGlass(ctx, input)
}

// UpgradeEpisode is the resolver for the upgradeEpisode field.
func (r *mutationResolver) UpgradeEpisode(ctx context.Context, input domain.OTPEpisodeUpgradeInput) (*domain.EpisodeOfCarePayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.UpgradeEpisode(ctx, input)
}

// EndEpisode is the resolver for the endEpisode field.
func (r *mutationResolver) EndEpisode(ctx context.Context, episodeID string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.EndEpisode(ctx, episodeID)
}

// StartEncounter is the resolver for the startEncounter field.
func (r *mutationResolver) StartEncounter(ctx context.Context, episodeID string) (string, error) {
	r.CheckUserTokenInContext(ctx)
	r.CheckDependencies()
	return r.usecases.StartEncounter(ctx, episodeID)
}

// EndEncounter is the resolver for the endEncounter field.
func (r *mutationResolver) EndEncounter(ctx context.Context, encounterID string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.EndEncounter(ctx, encounterID)
}

// RegisterPatient is the resolver for the registerPatient field.
func (r *mutationResolver) RegisterPatient(ctx context.Context, input domain.SimplePatientRegistrationInput) (*domain.PatientPayload, error) {
	r.CheckUserTokenInContext(ctx)
	r.CheckDependencies()
	return r.usecases.RegisterPatient(ctx, input)
}

// UpdatePatient is the resolver for the updatePatient field.
func (r *mutationResolver) UpdatePatient(ctx context.Context, input domain.SimplePatientRegistrationInput) (*domain.PatientPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.UpdatePatient(ctx, input)
}

// AddNextOfKin is the resolver for the addNextOfKin field.
func (r *mutationResolver) AddNextOfKin(ctx context.Context, input domain.SimpleNextOfKinInput) (*domain.PatientPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.AddNextOfKin(ctx, input)
}

// CreateUpdatePatientExtraInformation is the resolver for the createUpdatePatientExtraInformation field.
func (r *mutationResolver) CreateUpdatePatientExtraInformation(ctx context.Context, input domain.PatientExtraInformationInput) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateUpdatePatientExtraInformation(ctx, input)
}

// CreateFHIRMedicationRequest is the resolver for the createFHIRMedicationRequest field.
func (r *mutationResolver) CreateFHIRMedicationRequest(ctx context.Context, input domain.FHIRMedicationRequestInput) (*domain.FHIRMedicationRequestRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRMedicationRequest(ctx, input)
}

// UpdateFHIRMedicationRequest is the resolver for the updateFHIRMedicationRequest field.
func (r *mutationResolver) UpdateFHIRMedicationRequest(ctx context.Context, input domain.FHIRMedicationRequestInput) (*domain.FHIRMedicationRequestRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.UpdateFHIRMedicationRequest(ctx, input)
}

// DeleteFHIRMedicationRequest is the resolver for the deleteFHIRMedicationRequest field.
func (r *mutationResolver) DeleteFHIRMedicationRequest(ctx context.Context, id string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.DeleteFHIRMedicationRequest(ctx, id)
}

// CreateFHIRAllergyIntolerance is the resolver for the createFHIRAllergyIntolerance field.
func (r *mutationResolver) CreateFHIRAllergyIntolerance(ctx context.Context, input domain.FHIRAllergyIntoleranceInput) (*domain.FHIRAllergyIntoleranceRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRAllergyIntolerance(ctx, input)
}

// UpdateFHIRAllergyIntolerance is the resolver for the updateFHIRAllergyIntolerance field.
func (r *mutationResolver) UpdateFHIRAllergyIntolerance(ctx context.Context, input domain.FHIRAllergyIntoleranceInput) (*domain.FHIRAllergyIntoleranceRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.UpdateFHIRAllergyIntolerance(ctx, input)
}

// CreateFHIRCondition is the resolver for the createFHIRCondition field.
func (r *mutationResolver) CreateFHIRCondition(ctx context.Context, input domain.FHIRConditionInput) (*domain.FHIRConditionRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRCondition(ctx, input)
}

// UpdateFHIRCondition is the resolver for the updateFHIRCondition field.
func (r *mutationResolver) UpdateFHIRCondition(ctx context.Context, input domain.FHIRConditionInput) (*domain.FHIRConditionRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRCondition(ctx, input)
}

// CreateFHIRServiceRequest is the resolver for the createFHIRServiceRequest field.
func (r *mutationResolver) CreateFHIRServiceRequest(ctx context.Context, input domain.FHIRServiceRequestInput) (*domain.FHIRServiceRequestRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRServiceRequest(ctx, input)
}

// DeleteFHIRServiceRequest is the resolver for the deleteFHIRServiceRequest field.
func (r *mutationResolver) DeleteFHIRServiceRequest(ctx context.Context, id string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.DeleteFHIRServiceRequest(ctx, id)
}

// CreateFHIRObservation is the resolver for the createFHIRObservation field.
func (r *mutationResolver) CreateFHIRObservation(ctx context.Context, input domain.FHIRObservationInput) (*domain.FHIRObservationRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRObservation(ctx, input)
}

// CreateFHIRComposition is the resolver for the createFHIRComposition field.
func (r *mutationResolver) CreateFHIRComposition(ctx context.Context, input domain.FHIRCompositionInput) (*domain.FHIRCompositionRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIRComposition(ctx, input)
}

// UpdateFHIRComposition is the resolver for the updateFHIRComposition field.
func (r *mutationResolver) UpdateFHIRComposition(ctx context.Context, input domain.FHIRCompositionInput) (*domain.FHIRCompositionRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.UpdateFHIRComposition(ctx, input)
}

// DeleteFHIRComposition is the resolver for the deleteFHIRComposition field.
func (r *mutationResolver) DeleteFHIRComposition(ctx context.Context, id string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.DeleteFHIRComposition(ctx, id)
}

// DeleteFHIRPatient is the resolver for the deleteFHIRPatient field.
func (r *mutationResolver) DeleteFHIRPatient(ctx context.Context, id string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.DeleteFHIRPatient(ctx, id)
}

// DeleteFHIRObservation is the resolver for the deleteFHIRObservation field.
func (r *mutationResolver) DeleteFHIRObservation(ctx context.Context, id string) (bool, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.DeleteFHIRObservation(ctx, id)
}

// CreateFHIROrganization is the resolver for the createFHIROrganization field.
func (r *mutationResolver) CreateFHIROrganization(ctx context.Context, input domain.FHIROrganizationInput) (*domain.FHIROrganizationRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.CreateFHIROrganization(ctx, input)
}

// PatientHealthTimeline is the resolver for the patientHealthTimeline field.
func (r *queryResolver) PatientHealthTimeline(ctx context.Context, input domain.HealthTimelineInput) (*domain.HealthTimeline, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.PatientHealthTimeline(ctx, input)
}

// FindPatientsByMsisdn is the resolver for the findPatientsByMSISDN field.
func (r *queryResolver) FindPatientsByMsisdn(ctx context.Context, msisdn string) (*domain.PatientConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.FindPatientsByMSISDN(ctx, msisdn)
}

// FindPatients is the resolver for the findPatients field.
func (r *queryResolver) FindPatients(ctx context.Context, search string) (*domain.PatientConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.PatientSearch(ctx, search)
}

// GetPatient is the resolver for the getPatient field.
func (r *queryResolver) GetPatient(ctx context.Context, id string) (*domain.PatientPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.FindPatientByID(ctx, id)
}

// OpenEpisodes is the resolver for the openEpisodes field.
func (r *queryResolver) OpenEpisodes(ctx context.Context, patientReference string) ([]*domain.FHIREpisodeOfCare, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.OpenEpisodes(ctx, patientReference)
}

// OpenOrganizationEpisodes is the resolver for the openOrganizationEpisodes field.
func (r *queryResolver) OpenOrganizationEpisodes(ctx context.Context, providerSladeCode string) ([]*domain.FHIREpisodeOfCare, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.OpenOrganizationEpisodes(ctx, providerSladeCode)
}

// ProblemSummary is the resolver for the problemSummary field.
func (r *queryResolver) ProblemSummary(ctx context.Context, patientID string) ([]string, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.ProblemSummary(ctx, patientID)
}

// VisitSummary is the resolver for the visitSummary field.
func (r *queryResolver) VisitSummary(ctx context.Context, encounterID string) (map[string]interface{}, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.VisitSummary(ctx, encounterID, common.MaxClinicalRecordPageSize)
}

// PatientTimelineWithCount is the resolver for the patientTimelineWithCount field.
func (r *queryResolver) PatientTimelineWithCount(ctx context.Context, episodeID string, count int) ([]map[string]interface{}, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.PatientTimelineWithCount(ctx, episodeID, count)
}

// PatientTimeline is the resolver for the patientTimeline field.
func (r *queryResolver) PatientTimeline(ctx context.Context, patientID string, count int) ([]map[string]interface{}, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.PatientTimeline(ctx, patientID, count)
}

// SearchFHIREncounter is the resolver for the searchFHIREncounter field.
func (r *queryResolver) SearchFHIREncounter(ctx context.Context, params map[string]interface{}) (*domain.FHIREncounterRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIREncounter(ctx, params)
}

// SearchFHIRCondition is the resolver for the searchFHIRCondition field.
func (r *queryResolver) SearchFHIRCondition(ctx context.Context, params map[string]interface{}) (*domain.FHIRConditionRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRCondition(ctx, params)
}

// SearchFHIRAllergyIntolerance is the resolver for the searchFHIRAllergyIntolerance field.
func (r *queryResolver) SearchFHIRAllergyIntolerance(ctx context.Context, params map[string]interface{}) (*domain.FHIRAllergyIntoleranceRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRAllergyIntolerance(ctx, params)
}

// SearchFHIRObservation is the resolver for the searchFHIRObservation field.
func (r *queryResolver) SearchFHIRObservation(ctx context.Context, params map[string]interface{}) (*domain.FHIRObservationRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRObservation(ctx, params)
}

// SearchFHIRMedicationStatement is the resolver for the searchFHIRMedicationStatement field.
func (r *queryResolver) SearchFHIRMedicationStatement(ctx context.Context, params map[string]interface{}) (*domain.FHIRMedicationStatementRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRMedicationStatement(ctx, params)
}

// SearchFHIRMedicationRequest is the resolver for the searchFHIRMedicationRequest field.
func (r *queryResolver) SearchFHIRMedicationRequest(ctx context.Context, params map[string]interface{}) (*domain.FHIRMedicationRequestRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRMedicationRequest(ctx, params)
}

// SearchFHIRServiceRequest is the resolver for the searchFHIRServiceRequest field.
func (r *queryResolver) SearchFHIRServiceRequest(ctx context.Context, params map[string]interface{}) (*domain.FHIRServiceRequestRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRServiceRequest(ctx, params)
}

// SearchFHIRComposition is the resolver for the searchFHIRComposition field.
func (r *queryResolver) SearchFHIRComposition(ctx context.Context, params map[string]interface{}) (*domain.FHIRCompositionRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIRComposition(ctx, params)
}

// AllergySummary is the resolver for the allergySummary field.
func (r *queryResolver) AllergySummary(ctx context.Context, patientID string) ([]string, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.AllergySummary(ctx, patientID)
}

// GetMedicalData is the resolver for the getMedicalData field.
func (r *queryResolver) GetMedicalData(ctx context.Context, patientID string) (*domain.MedicalData, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.GetMedicalData(ctx, patientID)
}

// SearchOrganization is the resolver for the searchOrganization field.
func (r *queryResolver) SearchOrganization(ctx context.Context, params map[string]interface{}) (*domain.FHIROrganizationRelayConnection, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.SearchFHIROrganization(ctx, params)
}

// FindOrganizationByID is the resolver for the findOrganizationByID field.
func (r *queryResolver) FindOrganizationByID(ctx context.Context, organizationID string) (*domain.FHIROrganizationRelayPayload, error) {
	r.CheckDependencies()
	r.CheckUserTokenInContext(ctx)
	return r.usecases.FindOrganizationByID(ctx, organizationID)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
